#Пользователи
##Получить пользователя по email
GET http://localhost:6000/users/anon@anonimous.com HTTP/1.1

###

##Создать / зарегистрировать нового пользователя
POST http://localhost:6000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Bready",
  "email": "butter@bread.com",
  "avatarUrl": "",
  "type": "обычный",
  "password": "NotAT0ast",
  "favoriteOffers": []
}

###

##Авторизовать пользователя
POST http://localhost:6000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "destroyer@hacker.com",
  "password": "JustHackIt!"
}

###

##Обновить информацию о пользователе
PATCH http://localhost:6000/users/654aa5c3c40da95599f4a3c8 HTTP/1.1
Content-Type: application/json

{
  "name": "AirJordanoBruno"
}

###

##Обновить аватар пользователя
PATCH http://localhost:6000/users/6547f4b941c78f73a835b1d5/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0N2Y0Yjk0MWM3OGY3M2E4MzViMWQ1IiwiaWF0IjoxNjk5MzAwNzMzLCJleHAiOjE2OTk0NzM1MzN9.HOeibE9I8oJTYkhMGwtiDXSr5RmZNXVTXZIyTwSW3Kc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< /home/alien/Изображения/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

##Проверить аутентификацию
GET http://localhost:6000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkwOTM0LCJleHAiOjE2OTk1NjM3MzR9.3VFVmxrHcjv3KP_Hp7A_aPD5pjhjA4qw0ZJ9D33SRgE

###

##Добавить предложение в избранное
PATCH http://localhost:6000/users/favorite/654aa4be3c4f976eb362d4ae
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkwOTM0LCJleHAiOjE2OTk1NjM3MzR9.3VFVmxrHcjv3KP_Hp7A_aPD5pjhjA4qw0ZJ9D33SRgE
Content-Type: application/json

{
  "isFavorite": true
}

###
