#Предложения
## Получить список всех предложений / или точное количество при указании query параметра
GET http://localhost:4000/offers?count=150 HTTP/1.1

###

## Создать новое предложение
POST http://localhost:6000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkzNTMwLCJleHAiOjE2OTk1NjYzMzB9.0oRC4cVF-68Kb0hnPE6ZsPouUQTCkW0TEwXDN6dKT_g
Content-Type: application/json

{
  "name": "It is a title for Anon offer",
  "description": "It is a title for Anon offer. It is a title for Anon offer. It is a title for Anon offer",
  "postDate": "2023-09-18T18:05:00Z",
  "city": "Paris",
  "isPremium": true,
  "isFavorite": false,
  "rating": 1,
  "previewImage": "placeImage-01.jpg",
  "placeImages": [
    "placeImage-01.jpg",
    "placeImage-02.jpg",
    "placeImage-03.jpg",
    "placeImage-04.jpg",
    "placeImage-05.jpg",
    "placeImage-06.jpg"
  ],
  "type": "House",
  "roomsAmount": 5,
  "guestsAmount": 9,
  "price": 15012,
  "conveniences": [
    "Breakfast",
    "Washer",
    "Towels"
  ],
  "location": {
    "longitude": 12.133242,
    "latitude": 1.1234562
  }
}

###

##Показать предложение
GET http://localhost:4000/offers/655141283bde15af9abe4e87 HTTP/1.1

###

##Удалить предложение
DELETE http://localhost:6000/offers/654c0b7107d7cc18bc812fc8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkzNTMwLCJleHAiOjE2OTk1NjYzMzB9.0oRC4cVF-68Kb0hnPE6ZsPouUQTCkW0TEwXDN6dKT_g

###

##Обновить предложение
PATCH http://localhost:6000/offers/654ab0c4c1e580ff691bb0e5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkzNTMwLCJleHAiOjE2OTk1NjYzMzB9.0oRC4cVF-68Kb0hnPE6ZsPouUQTCkW0TEwXDN6dKT_g
Content-Type: application/json

{
  "description": "Amsterdam know is very cool city i this and this know my family and friends"
}

###

##Получение списка комментариев по идентификатору предложения

GET http://localhost:6000/offers/654b5b079e0d7757ac041700/comments HTTP/1.1

###

##Обновление превью предложения
PATCH http://localhost:6000/offers/654d12cab602dc1c8a910c04/preview HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkzNTMwLCJleHAiOjE2OTk1NjYzMzB9.0oRC4cVF-68Kb0hnPE6ZsPouUQTCkW0TEwXDN6dKT_g
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="previewImage"; filename="previewTest.png"
Content-Type: image/png

< /home/alien/Изображения/previewTest.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

##Обновление изображений предложения
PATCH http://localhost:6000/offers/654d12cab602dc1c8a910c04/images HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkzNTMwLCJleHAiOjE2OTk1NjYzMzB9.0oRC4cVF-68Kb0hnPE6ZsPouUQTCkW0TEwXDN6dKT_g
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="placeImages"; filename="previewTest.png"
Content-Type: image/png

/home/alien/Изображения/previewTest.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="placeImages"; filename="previewTest2.png"
Content-Type: image/png

/home/alien/Изображения/previewTest2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="placeImages"; filename="previewTest3.png"
Content-Type: image/png

/home/alien/Изображения/previewTest3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="placeImages"; filename="previewTest4.png"
Content-Type: image/png

/home/alien/Изображения/previewTest4.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="placeImages"; filename="previewTest5.png"
Content-Type: image/png

/home/alien/Изображения/previewTest5.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="placeImages"; filename="previewTest6.png"
Content-Type: image/png

/home/alien/Изображения/previewTest6.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

##Получение списка избранных предложений пользователя
GET http://localhost:6000/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkwOTM0LCJleHAiOjE2OTk1NjM3MzR9.3VFVmxrHcjv3KP_Hp7A_aPD5pjhjA4qw0ZJ9D33SRgE

###

##Получение списка премиум предложений для города
GET http://localhost:6000/offers/premium/Amsterdam HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFub25AYW5vbmltb3VzLmNvbSIsIm5hbWUiOiJBbm9uVXNlciIsImlkIjoiNjU0YWE1YzNjNDBkYTk1NTk5ZjRhM2M4IiwiaWF0IjoxNjk5MzkwOTM0LCJleHAiOjE2OTk1NjM3MzR9.3VFVmxrHcjv3KP_Hp7A_aPD5pjhjA4qw0ZJ9D33SRgE

###
